build:
	@component build

build/build.js:
	@component build --use component-filter/styles

build/build.css:
	@component build --use component-filter/scripts

.PHONY: build build/build.css build/build.js
